apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: <Harbor_IP>:<Harbor_Port>/petclinic/spring-petclinic-rest:<Image_Tag>
        ports:
        - containerPort: 9966
      imagePullSecrets:
      - name: harbor-credentials
